export const GET_ALL_BLOGS_REQUEST = "GET_ALL_BLOGS_REQUEST";
export const GET_ALL_BLOGS_FAILURE = "GET_ALL_BLOGS_FAILURE";
export const GET_ALL_BLOGS_SUCCESS = "GET_ALL_BLOGS_SUCCESS";

export const POST_BLOG_REQUEST = "POST_BLOG_REQUEST";
export const POST_BLOG_FAILURE = "POST_BLOG_FAILURE";
export const POST_BLOG_SUCCESS = "POST_BLOG_SUCCESS";

export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";